name: 'Build & Push Docker Image Guacd'

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t xerxist/guacd:1.4.${{ github.run_number }} .
    - name: Build Docker Image latest tag
      run: docker build -t xerxist/guacd:latest .
    - name: Push Image
      run: docker push xerxist/guacd:${{ github.run_number }}
    - name: Push Image latest
      run: docker push xerxist/guacd:latest
